// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToAudio(arg1) {
  return window['go']['main']['App']['ConvertToAudio'](arg1);
}

export function SelectVideo() {
  return window['go']['main']['App']['SelectVideo']();
}

export function TranscribeAPI(arg1, arg2) {
  return window['go']['main']['App']['TranscribeAPI'](arg1, arg2);
}
