package download

import (
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// B站的反爬 WAF（HTTP 412）要求请求携带 buvid3 等 cookie。
// 这些 cookie 在访问 B站首页时由服务端 Set-Cookie 下发（匿名即可，无需登录）。
// 下载器在检测到 B站链接时自动维护一个匿名 cookie 文件并传给 yt-dlp 的 --cookies。
//
// 实现注意：不能用 Go cookiejar.Cookies() 的返回值写 Netscape 文件——
// 它对 host-only cookie 返回空的 Domain/Path，写出的文件 yt-dlp 加载不到。
// 这里直接解析重定向链上所有 Set-Cookie 原始头，保留 Domain/Path 属性。

const biliCookieTTL = 7 * 24 * time.Hour

const browserUA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

type collectedCookie struct {
	name    string
	value   string
	domain  string
	path    string
	secure  bool
	expires time.Time
}

func secureFlag(secure bool) string {
	if secure {
		return "TRUE"
	}
	return "FALSE"
}

func isBilibiliURL(mediaURL string) bool {
	return strings.Contains(strings.ToLower(mediaURL), "bilibili.com")
}

/** 解析一条 Set-Cookie 头；Domain 缺省为响应主机，Path 缺省为 "/" */
func parseSetCookie(raw string, fallbackHost string) (collectedCookie, bool) {
	parts := strings.Split(raw, ";")
	kv := strings.SplitN(parts[0], "=", 2)
	if len(kv) != 2 {
		return collectedCookie{}, false
	}
	cc := collectedCookie{
		name:    strings.TrimSpace(kv[0]),
		value:   strings.TrimSpace(kv[1]),
		domain:  fallbackHost,
		path:    "/",
		expires: time.Now().Add(180 * 24 * time.Hour),
	}
	if cc.name == "" {
		return collectedCookie{}, false
	}
	for _, attr := range parts[1:] {
		ka := strings.SplitN(strings.TrimSpace(attr), "=", 2)
		key := strings.ToLower(ka[0])
		value := ""
		if len(ka) == 2 {
			value = strings.TrimSpace(ka[1])
		}
		switch key {
		case "domain":
			cc.domain = strings.ToLower(strings.TrimPrefix(value, "."))
		case "path":
			if value != "" {
				cc.path = value
			}
		case "secure":
			cc.secure = true
		case "expires":
			if t, err := http.ParseTime(value); err == nil {
				cc.expires = t
			}
		}
	}
	return cc, true
}

/** 把 cookie 写成 Netscape 格式（yt-dlp --cookies 的输入格式），域含前导点表示含子域 */
func writeNetscapeCookieFile(path string, cookies []collectedCookie) error {
	var b strings.Builder
	b.WriteString("# Netscape HTTP Cookie File\n")
	b.WriteString("# Generated by FlexViword\n")
	for _, c := range cookies {
		// Netscape 惯例：布尔字段必须大写 TRUE/FALSE（Python stdlib 有
		// assert domain_specified == initial_dot 校验，小写会导致加载失败）
		domain := "." + strings.TrimPrefix(c.domain, ".")
		line := strings.Join(
			[]string{
				domain,
				"TRUE",
				c.path,
				secureFlag(c.secure),
				strconv.FormatInt(c.expires.Unix(), 10),
				c.name,
				c.value,
			},
			"\t",
		)
		b.WriteString(line + "\n")
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

/**
 * 为 B站链接准备匿名 cookie 文件，返回文件路径（非 B站链接返回 ""）。
 * 文件缓存在临时目录，TTL 内复用，避免每次下载都访问 B站首页。
 */
func ensureBilibiliCookies(mediaURL string) (string, error) {
	if !isBilibiliURL(mediaURL) {
		return "", nil
	}
	jarPath := filepath.Join(os.TempDir(), "flexviword-bili-cookies.txt")
	if info, err := os.Stat(jarPath); err == nil && time.Since(info.ModTime()) < biliCookieTTL {
		return jarPath, nil // 缓存仍新鲜
	}

	var collected []collectedCookie
	client := &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			if req.Response != nil {
				collectFromResponse(req.Response, &collected)
			}
			if len(via) >= 5 {
				return errors.New("too many redirects")
			}
			return nil
		},
	}

	req, err := http.NewRequest("GET", "https://www.bilibili.com/", nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("User-Agent", browserUA)
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("访问 bilibili.com 失败: %w", err)
	}
	collectFromResponse(resp, &collected)
	resp.Body.Close()

	// 按名字去重（重定向链可能重复下发），后到覆盖先到
	byName := make(map[string]collectedCookie)
	for _, cc := range collected {
		byName[cc.name] = cc
	}
	if len(byName) == 0 {
		return "", fmt.Errorf("未能获取 B站 cookie")
	}

	final := make([]collectedCookie, 0, len(byName))
	for _, cc := range byName {
		// WAF 挑战令牌（X-BILI-SEC-TOKEN 等，X- 前缀）绑定了采集时的
		// TLS 指纹/IP，回放给 yt-dlp 反而触发 412 —— 必须丢弃
		if strings.HasPrefix(cc.name, "X-") {
			continue
		}
		domain := "." + strings.TrimPrefix(cc.domain, ".")
		final = append(final, collectedCookie{domain: domain, path: cc.path, secure: cc.secure, expires: cc.expires, name: cc.name, value: cc.value})
	}
	if len(final) == 0 {
		return "", fmt.Errorf("未能获取 B站 cookie")
	}
	return jarPath, nil
}

func collectFromResponse(resp *http.Response, out *[]collectedCookie) {
	host := resp.Request.URL.Hostname()
	for _, raw := range resp.Header.Values("Set-Cookie") {
		if cc, ok := parseSetCookie(raw, host); ok {
			*out = append(*out, cc)
		}
	}
}
